[Feat] 전통적인 방식의 로그인 구현 + 시큐리티 구현 !
DiscordStudy/PublicCalender pull request #15
Opened 2024-09-02 06:56 UTC by prozen99

# ⭐️ Pull Request 요약

전통적인 방식의 로그인 구현 과 시큐리티 구현을 했습니다 ! 

## 🛠️ 변경 사항

LoginRequest : 사용자가 로그인 요청을 할 때 쓰는 dto 입니다 loginid와 password를 보내는 역할을 합니다

MemberController : 요청 body로 loginRequest를 받아서 Service 로직의 authenticate 메서드를 불러와서 이 사용자가 실제 db에 저장되어 있는 ( 회원가입이 되어있는지 ) 확인 하고 성공하면 ok 실패하면 401 오류를 뱉습니다

MemberService :  authenticate 메서드는 memberRepository에 실제 사용자의 로그인 id가 있는지 체크 함 ! 

MemberRepository : findByLoginId(String loginId) 를 추가함  loginid를 기준으로 탐색하기 위해서 추가 

SecurityConfig : 로그인 부분인 "/members/login " 경로 추가 

password 인코딩을 위해서 password bean을 추가함 

## 💡 관련 이슈

- #9번 작업입니다

## ⏱️ 작업 기간

- 작업 시작일: (2024-09-02)
- 작업 종료일: (2024-09-02)

## 📌 유의사항

## 🔗 참고문헌

## 💡 새롭게 알게 된 사실

JpaRepository 는 CrudRepository를 상속받음 = > 그래서 save findby같은 메서드를 사용할 수 있었음

쿼리 메서드의 명명 규칙

ex ) findByName()  = > name컬럼의 값중 파라미터로 들어오는 값과 같은 데이터 반환 

만약 findbyLogin(String loginId) 라면 = > 파라미터인 String loginid와 같은값 반환

sql 쿼리는 WHERE loginid=#{loginid} 로 요청함 !

2024-09-02 07:21 UTC, Galmaeki requested changes
다른 리뷰는 크게 상관 없으나 로그인 디코딩하는 부분은 변경이 필요함

2024-09-02 07:21 UTC, Galmaeki commented on src/main/java/discordstudy/calender/domain/member/controller/MemberController.java
> +        }
36번줄에서 return을 했다면 38, 40번 라인이 없어도 될 것 같음

2024-09-02 07:21 UTC, Galmaeki commented on src/main/java/discordstudy/calender/global/config/SecurityConfig.java
> +                        .requestMatchers("/","/members/signup","/members/login").permitAll()//
```java
.authorizeHttpRequests((requests)->requests
        .requestMatchers("/").permitAll()
        .requestMatchers(HttpMethod.POST,"/members/signup","/members/login").permitAll()
        .anyRequest().authenticated()
)
```
와일드카드(*)를 사용하지 않고 상세한 경로로 제한했다면 이렇게 메소드도 제한하는 것이 일관성 있어보임
나중을 위해 도메인별로 requestMatchers를 따로 사용하면 경로가 늘어났을 때 가독성이 좋아짐

2024-09-02 07:21 UTC, Galmaeki commented on src/main/java/discordstudy/calender/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new IllegalArgumentException("유효하지 않은 로그인 아이디 나 패스워드 입니다"));
#16 번 PR이 머지 된 이후 ApplicationException 으로 변경 할 것!

2024-09-02 07:21 UTC, Galmaeki commented on src/main/java/discordstudy/calender/domain/member/service/MemberService.java
> +        //맞으면 true 아니면 false를 가짐
회원 가입 시 인코딩을 하지 않는데 로그인 할 때만 디코딩 하고 있음

2024-09-02 08:11 UTC, prozen99 commented on src/main/java/discordstudy/calender/domain/member/service/MemberService.java
> +
이 부분 헷갈리는게 이러면 
28~29 번 라인의 코드 의미대로 먼저 loginid가 db에 있는지 체크한다음에 

passwordEncoder에서 비밀번호가 같은 애들을 찾는거인데

내가 아직 예외 처리를 안한거 같은데 아이디가 중복 되면 어떤일이 벌어질지 예상이 안가네

2024-09-02 08:11 UTC, prozen99 commented on src/main/java/discordstudy/calender/domain/member/controller/MemberController.java
> +        }
36 return하라는게 그냥 성공시 ok만 두고 실패할때는 따로 처리 안해도 된다는 말이지?

2024-09-02 08:11 UTC, prozen99 commented on src/main/java/discordstudy/calender/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new IllegalArgumentException("유효하지 않은 로그인 아이디 나 패스워드 입니다"));
16번 머지 되면 그렇게 할게

2024-09-02 08:11 UTC, prozen99 commented on src/main/java/discordstudy/calender/domain/member/service/MemberService.java
> +        //맞으면 true 아니면 false를 가짐
.matches가 password를 디코딩해서 찾는 메서드네

2024-09-02 08:11 UTC, prozen99 commented on src/main/java/discordstudy/calender/global/config/SecurityConfig.java
> +                        .requestMatchers("/","/members/signup","/members/login").permitAll()//
이렇게 보니까 일단은 와일드 카드가 조금 더 편해보이긴하네

2024-09-02 08:15 UTC, Galmaeki commented on src/main/java/discordstudy/calender/domain/member/controller/MemberController.java
> +        }
```java
    @PostMapping("/login")
    public ResponseEntity<ApiResponse<Void>> login(@RequestBody LoginRequest request)
    {
        boolean authenticate = memberService.authenticate(request);
        if(authenticate)//회원가입이 성공한 회원 ! 이라면
        {
            return ResponseEntity.ok().build();//로그인 성공시 ok를 보내고 싶음
        }
         return ResponseEntity.status(401).build();
    }
```
else를 없애도 된다고 한거임

2024-09-02 08:31 UTC, Galmaeki commented on src/main/java/discordstudy/calender/domain/member/service/MemberService.java
> +
지금 회원가입이나 엔티티 자체에서 Id를 유니크 제약을 안줬기 때문에 loginId가 같아도 회원가입이 가능한 상태

이대로 DB에 같은 id 2개 가 존재하는데 Optional로 1개만 찾아오는 코드라서 DataAccessException 이 발생할 것으로 예상됨

2024-09-03 15:14 UTC, prozen99 commented
인코딩 디코딩 다했습니다 머지해주세요 !

2024-09-03 15:24 UTC, Galmaeki approved these changes
확인했스빈다
제안사항 있는데 확인하고 할거면 하고 안할거면 본인이 머지해주세오

2024-09-03 15:24 UTC, Galmaeki commented on src/main/java/discordstudy/calender/domain/member/controller/MemberController.java
>          SignupResponse response=new SignupResponse(savedMember);
굳이 할당 할 필요 없음

2024-09-03 15:24 UTC, Galmaeki commented on src/main/java/discordstudy/calender/domain/member/service/MemberService.java
>      }
반환타입을 void 로 변경해도 될듯

2024-09-03 15:30 UTC, Galmaeki reviewed
[위에 제안사항 부분](https://github.com/DiscordStudy/PublicCalender/pull/15#discussion_r1742254250)확인하고 받아들일지 말지 판단해서 직접 머지하세오

2024-09-03 15:32 UTC, merged