[Feat] 팀 생성 기능 개발
DiscordStudy/PublicCalender pull request #26
Opened 2024-09-09 08:43 UTC by prozen99

# ⭐️ Pull Request 요약

- 팀 생성 기능 개발 

## 🛠️ 변경 사항

- 이전 PR을 지우고 , 아예 새롭게 Repository ,Service,Controller를 구성했음 . 

## 💡 관련 이슈

-  #24 

## ⏱️ 작업 기간

- 작업 시작일: (2024-09-09)
- 작업 종료일: (2024-09-09)

## 📌 유의사항

- 이 PR로부터 발생할 수 있는 유의사항이나 다른 PR에 미칠 영향들에 대한 설명

![image](https://github.com/user-attachments/assets/7db3c4e4-6b5e-4592-8cbd-b1e2413168a1)

2024-09-09 08:52 UTC, Galmaeki requested changes
코멘트 확인 해주새오

2024-09-09 08:52 UTC, Galmaeki commented on src/main/java/discordstudy/calender/domain/team/service/TeamService.java
> +    }
Team 엔티티 자체를 반환하지 말고 id만 반환할것
엔티티를 컨트롤러까지 올려보내지 말것

2024-09-09 08:52 UTC, Galmaeki commented on src/main/java/discordstudy/calender/domain/team/controller/TeamController.java
> +    }
API 명세서 다시 확인할것
- 명세서
```json
{
    "status": 200,
    "message": "Success",
    "data": {
        "teamId": 1
    }
}
```
- 현재 구현 한 것
```json
{
    "status": 200,
    "message": "Success",
    "data": 1
}
```

2024-09-09 08:52 UTC, Galmaeki commented on src/main/java/discordstudy/calender/global/config/SecurityConfig.java
> +                        .requestMatchers("/", "/members/*","/team").permitAll()//
경로 확인

2024-09-09 08:52 UTC, Galmaeki commented on src/main/java/discordstudy/calender/global/config/SecurityConfig.java
개행 너무 많음

2024-09-10 09:10 UTC, prozen99 commented on src/main/java/discordstudy/calender/domain/team/controller/TeamController.java
> +    }
아직 구현 안했었네요 각주 지우고 수정예정입니다

2024-09-10 09:10 UTC, prozen99 commented on src/main/java/discordstudy/calender/domain/team/service/TeamService.java
> +    }
엔티티를 Controller 까지 안보내고 id만 반환하도록 했습니다

2024-09-10 09:10 UTC, prozen99 commented on src/main/java/discordstudy/calender/domain/team/service/TeamService.java
> +    }
수정했습니다

2024-09-10 09:11 UTC, prozen99 commented on src/main/java/discordstudy/calender/domain/team/controller/TeamController.java
> +    }
수정했습니다 객체로 한번더 감싸서

2024-09-10 09:11 UTC, prozen99 commented on src/main/java/discordstudy/calender/global/config/SecurityConfig.java
> +                        .requestMatchers("/", "/members/*","/team").permitAll()//
경로 고쳤습니다 !

2024-09-10 09:19 UTC, Galmaeki requested changes
미완성인 부분 완성해주세요
수정사항, 질문사항 댓글 남겻서오

2024-09-10 09:19 UTC, Galmaeki commented on src/main/java/discordstudy/calender/domain/team/dto/TeamResponse.java
> +    }
롬복 사용하지 않은 이유가 있나요?

2024-09-10 09:19 UTC, Galmaeki commented on src/main/java/discordstudy/calender/domain/team/service/TeamService.java
> +    }
트랜잭션이 안 걸려있네요
걸어주새오

2024-09-10 09:19 UTC, Galmaeki commented on src/main/java/discordstudy/calender/global/config/SecurityConfig.java
>                          .requestMatchers("/", "/members/*").permitAll()//
"/"경로 제거해주세요
일단 api 서버만 만들고 있으니까요

2024-09-10 09:23 UTC, prozen99 commented on src/main/java/discordstudy/calender/global/config/SecurityConfig.java
>                          .requestMatchers("/", "/members/*").permitAll()//
수정했습니다

2024-09-10 09:24 UTC, prozen99 commented on src/main/java/discordstudy/calender/domain/team/dto/TeamResponse.java
> +    }
AllArgumentConstructor가 손에 안익어서 썻는데 롬복이 가독성 더좋으니까 수정할게요

2024-09-27 03:32 UTC, Galmaeki commented
댓글 정리용으로 PR 닫스빈다
필요하면 새로 PR 날리새오

2024-09-27 03:32 UTC, closed without merging